.TH MD2MAN\-RAKE 1                   2018\-02\-04                            5.1.2
.SH NAME
.PP
md2man\-rake \- run 
.BR rake (1) 
tasks from 
.BR md2man (1)
.SH SYNOPSIS
.PP
\fB\fCmd2man\-rake\fR [\fIOPTION\fP]... [\fITASK\fP]...
.SH DESCRIPTION
.PP
This program lets you run 
.BR rake (1) 
tasks provided by 
.BR md2man (1) 
without having
to create a special file named \fB\fCRakefile\fR that contains the following snippet:
.PP
.RS
.nf
require 'md2man/rakefile'
.fi
.RE
.PP
If no \fITASK\fP is specified, then the \fB\fCmd2man\fR task is run by default.
.SH TASKS
.TP
\fB\fCmd2man\fR
Runs the \fB\fCmd2man:man\fR and \fB\fCmd2man:web\fR tasks, in that order.
.TP
\fB\fCmd2man:man\fR or \fB\fCman\fR
Builds UNIX manual pages from \fB\fC*.markdown\fR, \fB\fC*.mkd\fR, and \fB\fC*.md\fR files
found in or beneath the \fB\fCman/\fR subdirectory in your working directory.
.TP
\fB\fCmd2man:web\fR or \fB\fCweb\fR
Builds HTML manual pages from \fB\fC*.markdown\fR, \fB\fC*.mkd\fR, and \fB\fC*.md\fR files
found in or beneath the \fB\fCman/\fR subdirectory in your working directory.
.SH OPTIONS
.TP
\fB\fC\-h\fR [\fIPATTERN\fP], \fB\fC\-\-help\fR [\fIPATTERN\fP]
Show this help manual and optionally search for \fIPATTERN\fP regular expression.
.TP
\&...
Anything else is passed to 
.BR rake (1); 
run \fB\fCrake \-\-help\fR for documentation.
.SH SEE ALSO
.PP
.BR rake (1), 
.BR md2man-roff (1), 
.BR md2man-html (1), 
.BR md2man (5)
