.TH MD2MAN\-ROFF 1                   2018\-02\-04                            5.1.2
.SH NAME
.PP
md2man\-roff \- convert 
.BR md2man (5) 
flavored Markdown \[la]http://daringfireball.net/projects/markdown/syntax\[ra] text into 
.BR roff (7)
.SH SYNOPSIS
.PP
\fB\fCmd2man\-roff\fR [\fIOPTION\fP]... [\fIFILE\fP]
.SH DESCRIPTION
.PP
This program converts the 
.BR md2man (5) 
flavored Markdown \[la]http://daringfireball.net/projects/markdown/syntax\[ra] text from the given
\fIFILE\fP into 
.BR roff (7) 
and then prints the result to the standard output stream.
If \fIFILE\fP is not given, then the standard input stream is read in its place.
.SS Limitations
.PP
This program does not convert the following Redcarpet \[la]https://github.com/vmg/redcarpet\[ra] nodes into 
.BR roff (7):
.RS
.IP \(bu 2
\fB\fCblock_html\fR
.IP \(bu 2
\fB\fCstrikethrough\fR
.IP \(bu 2
\fB\fCsuperscript\fR
.IP \(bu 2
\fB\fCimage\fR
.IP \(bu 2
\fB\fCraw_html\fR
.RE
.PP
It issues a warning when it encounters these instead.  Patches are welcome!
.SH OPTIONS
.TP
\fB\fC\-h\fR [\fIPATTERN\fP], \fB\fC\-\-help\fR [\fIPATTERN\fP]
Show this help manual and optionally search for \fIPATTERN\fP regular expression.
.SH SEE ALSO
.PP
.BR md2man-html (1), 
.BR md2man-rake (1), 
.BR md2man (5), 
Markdown \[la]http://daringfireball.net/projects/markdown/syntax\[ra]
